spring:
  server:
    port: 8080
  profiles:
    active: dev
  datasource:
    username: root
    password: ForMe=520
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com

#showSql
logging:
  level:
    com:
      example:
        mapper : debug